---
- name: Configure application
  hosts: all
  become: true
  become_method: sudo
  tasks:
    - name: Install packages
      become: true
      apt: state=latest update_cache=yes name={{ item }} state=present
      with_items:
        - curl
